// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversitySystem.Models;
using UniversitySystem.Data;

#nullable disable

namespace UniversitySystem.Migrations
{
    [DbContext(typeof(UniversityContext))]
    partial class UniversityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversitySystem.Models.Departament", b =>
                {
                    b.Property<int>("IdDepartament")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartament"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDepartament");

                    b.ToTable("Departaments");
                });

            modelBuilder.Entity("UniversitySystem.Models.Discipline", b =>
                {
                    b.Property<int>("IdDiscipline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDiscipline"));

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdDiscipline");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("UniversitySystem.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<DateTime?>("DateBirthday")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdGroup")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdGroup");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("UniversitySystem.Models.StudentGroup", b =>
                {
                    b.Property<int>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGroup"));

                    b.Property<int?>("IdDepartament")
                        .HasColumnType("int");

                    b.Property<int?>("NumberGroup")
                        .HasColumnType("int");

                    b.HasKey("IdGroup");

                    b.HasIndex("IdDepartament");

                    b.ToTable("StudentGroups");
                });

            modelBuilder.Entity("UniversitySystem.Models.Teacher", b =>
                {
                    b.Property<int>("IdTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeacher"));

                    b.Property<int?>("IdDepartament")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patronymic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdTeacher");

                    b.HasIndex("IdDepartament");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("UniversitySystem.Models.Student", b =>
                {
                    b.HasOne("UniversitySystem.Models.StudentGroup", "Group")
                        .WithMany("Students")
                        .HasForeignKey("IdGroup");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("UniversitySystem.Models.StudentGroup", b =>
                {
                    b.HasOne("UniversitySystem.Models.Departament", "Departament")
                        .WithMany("StudentGroups")
                        .HasForeignKey("IdDepartament");

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("UniversitySystem.Models.Teacher", b =>
                {
                    b.HasOne("UniversitySystem.Models.Departament", "Departament")
                        .WithMany("Teachers")
                        .HasForeignKey("IdDepartament");

                    b.Navigation("Departament");
                });

            modelBuilder.Entity("UniversitySystem.Models.Departament", b =>
                {
                    b.Navigation("StudentGroups");

                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("UniversitySystem.Models.StudentGroup", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
